name: "build"

on:
  workflow_dispatch:

  push:
    branches:
      - main
    tags:
      - v*

  pull_request:

  schedule:
    - cron: '0 0 * * 1'

jobs:

  native-build-download-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout roc-pulse
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          ./scripts/install_system_dependencies.sh

      - name: Build roc-pulse
        run: |
          mkdir build
          cd build
          cmake ..
          make VERBOSE=1

      - name: Install roc-pulse
        run: |
          sudo make install

  native-build-system-roc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout roc-pulse
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          ./scripts/install_system_dependencies.sh

      - name: Download roc-toolkit
        run: |
          ./scripts/download_roc.sh ./roc-toolkit

      - name: Build and install roc-toolkit
        run: |
          ./scripts/build_and_install_roc.sh ./roc-toolkit /usr/local

      - name: Build roc-pulse
        run: |
          set -ex
          mkdir build
          cd build
          cmake .. -DDOWNLOAD_ROC=OFF
          make VERBOSE=1

      - name: Install roc-pulse
        run: |
          sudo make install

  native-build-external-roc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout roc-pulse
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          ./scripts/install_system_dependencies.sh

      - name: Download roc-toolkit
        run: |
          ./scripts/download_roc.sh ./roc-toolkit

      - name: Build and install roc-toolkit
        run: |
          ./scripts/build_and_install_roc.sh ./roc-toolkit ./roc-install

      - name: Build roc-pulse
        run: |
          set -ex
          mkdir build
          cd build
          cmake .. \
            -DDOWNLOAD_ROC=OFF \
            -DROC_INCLUDE_DIR=./roc-install/include \
            -DROC_LIB_DIR=./roc-install/lib
          make VERBOSE=1

      - name: Install roc-pulse
        run: |
          sudo make install

  native-build-external-pulse-and-system-libtool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          ./scripts/install_system_dependencies.sh

      - name: Download pulseaudio
        run: |
          ./scripts/download_pulseaudio.sh ./pulseaudio "12.2"

      - name: Build roc-pulse
        run: |
          set -ex
          mkdir build
          cd build
          cmake .. \
            -DDOWNLOAD_PULSEAUDIO=OFF \
            -DDOWNLOAD_LIBTOOL=OFF \
            -DPULSEAUDIO_DIR=./pulseaudio \
            -DPULSEAUDIO_VERSION=12.2
          make VERBOSE=1

      - name: Install roc-pulse
        run: |
          sudo make install

  cross-build-download-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout roc-pulse
        uses: actions/checkout@v2

      - uses: addnab/docker-run-action@v3
        with:
          image: rocstreaming/toolchain-aarch64-linux-gnu
          options: -v ${{ github.workspace }}:/work -w /work -eCI=1
          run: |
            set -ex
            mkdir build
            cd build
            cmake .. -DHOST=aarch64-linux-gnu -DPULSEAUDIO_VERSION=12.2
            make VERBOSE=1

  cross-build-external-roc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout roc-pulse
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          ./scripts/install_system_dependencies.sh

      - name: Download roc-toolkit
        run: |
          ./scripts/download_roc.sh ./roc-toolkit

      - uses: addnab/docker-run-action@v3
        with:
          image: rocstreaming/toolchain-aarch64-linux-gnu
          options: -v ${{ github.workspace }}:/work -w /work -eCI=1
          run: |
            set -ex
            ./scripts/build_and_install_roc.sh ./roc-toolkit ./roc-install aarch64-linux-gnu
            mkdir build
            cd build
            cmake .. \
              -DHOST=aarch64-linux-gnu \
              -DDOWNLOAD_ROC=OFF \
              -DROC_INCLUDE_DIR=./roc-install/include \
              -DROC_LIB_DIR=./roc-install/lib \
              -DPULSEAUDIO_VERSION=12.2
            make VERBOSE=1

  cross-build-external-pulse-and-libtool:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download pulseaudio
        run: |
          ./scripts/download_pulseaudio.sh ./pulseaudio "12.2"

      - name: Download libtool
        run: |
          ./scripts/download_libtool.sh ./libtool "2.4.6"

      - uses: addnab/docker-run-action@v3
        with:
          image: rocstreaming/toolchain-aarch64-linux-gnu
          options: -v ${{ github.workspace }}:/work -w /work -eCI=1
          run: |
            set -ex
            mkdir build
            cd build
            cmake .. \
              -DHOST=aarch64-linux-gnu \
              -DDOWNLOAD_PULSEAUDIO=OFF \
              -DPULSEAUDIO_DIR=./pulseaudio \
              -DPULSEAUDIO_VERSION=12.2 \
              -DDOWNLOAD_LIBTOOL=OFF \
              -DLIBTOOL_DIR=./libtool
            make VERBOSE=1

  pulse-versions:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        pulse_version:
          - "4.0"
          - "5.0"
          - "8.0"
          - "10.0"
          - "11.1"
          - "12.2"
          - "13.99.1"
          - "14.2"

    name: pulse-versions/${{ matrix.pulse_version }}
    steps:
      - name: Checkout roc-pulse
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          ./scripts/install_system_dependencies.sh

      - name: Build roc-pulse
        run: |
          set -ex
          mkdir build
          cd build
          cmake .. -DPULSEAUDIO_VERSION=${{ matrix.pulse_version }}
          make VERBOSE=1

  linux-versions:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: ubuntu-20.04
            image: rocstreaming/env-ubuntu:20.04

          - distro: ubuntu-18.04
            image: rocstreaming/env-ubuntu:18.04

          - distro: ubuntu-16.04
            image: rocstreaming/env-ubuntu:16.04

    name: linux-versions/${{ matrix.distro }}
    steps:
      - name: Checkout roc-pulse
        uses: actions/checkout@v2

      - uses: addnab/docker-run-action@v3
        with:
          image: ${{ matrix.image }}
          options: -v ${{ github.workspace }}:/work -w /work -eCI=1
          run: |
            set -ex
            mkdir build
            cd build
            cmake ..
            make VERBOSE=1
            make install

  toolchains:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - toolchain: aarch64-linux-gnu
            image: rocstreaming/toolchain-aarch64-linux-gnu:gcc-7.4

          - toolchain: arm-linux-gnueabihf
            image: rocstreaming/toolchain-arm-linux-gnueabihf:gcc-4.9

          - toolchain: arm-bcm2708hardfp-linux-gnueabi
            image: rocstreaming/toolchain-arm-bcm2708hardfp-linux-gnueabi:gcc-4.7

    name: toolchains/${{ matrix.toolchain }}
    steps:
      - name: Checkout roc-pulse
        uses: actions/checkout@v2

      - uses: addnab/docker-run-action@v3
        with:
          image: ${{ matrix.image }}
          options: -v ${{ github.workspace }}:/work -w /work -eCI=1
          run: |
            set -ex
            mkdir build
            cd build
            cmake .. -DHOST=${{ matrix.toolchain }} -DPULSEAUDIO_VERSION=12.2
            make VERBOSE=1
