name: "build"

on:
  workflow_dispatch:

  push:
    branches:
      - main
    tags:
      - v*

  pull_request:

  schedule:
    - cron: '0 0 * * 1'

jobs:

  native-build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: ubuntu-20.04
            image: rocstreaming/env-ubuntu:20.04

          - distro: ubuntu-18.04
            image: rocstreaming/env-ubuntu:18.04

          - distro: ubuntu-16.04
            image: rocstreaming/env-ubuntu:16.04

          - distro: debian
            image: rocstreaming/env-debian

          - distro: fedora
            image: rocstreaming/env-fedora

          - distro: opensuse
            image: rocstreaming/env-opensuse

          - distro: archlinux
            image: rocstreaming/env-archlinux

          - distro: alpine
            image: rocstreaming/env-alpine

    name: native-build/${{ matrix.distro }}
    steps:
      - name: Checkout roc-pulse
        uses: actions/checkout@v2

      - name: Checkout roc-toolkit
        run: |
          ./script/download_roc.sh ./roc-toolkit

      - uses: addnab/docker-run-action@v3
        with:
          image: ${{ matrix.image }}
          options: -v ${{ github.workspace }}:/work -w /work -eCI=1
          run: |
            set -ex
            ./script/build_and_install_roc.sh ./roc-toolkit /usr
            mkdir build
            cd build
            cmake ..
            make -j2 VERBOSE=1

  cross-build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - toolchain: aarch64-linux-gnu
            image: rocstreaming/toolchain-aarch64-linux-gnu:gcc-7.4

          - toolchain: arm-linux-gnueabihf
            image: rocstreaming/toolchain-arm-linux-gnueabihf:gcc-4.9

          - toolchain: arm-bcm2708hardfp-linux-gnueabi
            image: rocstreaming/toolchain-arm-bcm2708hardfp-linux-gnueabi:gcc-4.7

    name: cross-compile/${{ matrix.toolchain }}
    steps:
      - name: Checkout roc-pulse
        uses: actions/checkout@v2

      - name: Checkout roc-toolkit
        run: |
          ./script/download_roc.sh ./roc-source

      - uses: addnab/docker-run-action@v3
        with:
          image: ${{ matrix.image }}
          options: -v ${{ github.workspace }}:/work -w /work -eCI=1
          run: |
            set -ex
            ./script/build_and_install_roc.sh ./roc-source ./roc-install ${{ matrix.toolchain }}
            mkdir build
            cd build
            cmake .. \
              -DHOST=${{ matrix.toolchain }} \
              -DROC_INCLUDE_DIR=./roc-install/include \
              -DROC_LIBRARY_DIR=./roc-install/lib
            make -j2 VERBOSE=1

  external-pulse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          ./script/install_system_dependencies.sh

      - name: Build pulseaudio
        run: |
          ./script/download_and_build_pulseaudio.sh ./pulse ./pulse

      - name: Build and install roc-toolkit
        run: |
          ./script/download_roc.sh ./roc-toolkit
          ./script/build_and_install_roc.sh ./roc-toolkit /usr

      - name: Build and install roc-pulse
        run: |
            mkdir build
            cd build
            cmake .. -DPULSEAUDIO_SOURCE_DIR=./pulse
            make -j2 VERBOSE=1
            sudo make install

  external-pulse-out-of-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          ./script/install_system_dependencies.sh

      - name: Build pulseaudio
        run: |
          ./script/download_and_build_pulseaudio.sh ./pulse-source ./pulse-build

      - name: Build and install roc-toolkit
        run: |
          ./script/download_roc.sh ./roc-toolkit
          ./script/build_and_install_roc.sh ./roc-toolkit /usr

      - name: Build and install roc-pulse
        run: |
            mkdir build
            cd build
            cmake .. \
              -DPULSEAUDIO_SOURCE_DIR=./pulse-source \
              -DPULSEAUDIO_BUILD_DIR=./pulse-build
            make -j2 VERBOSE=1
            sudo make install
